server:
  port: 18764

spring:
  application:
    name: spring-cloud-trace

#监控信息
management:
  endpoints:
    web:
      #设置对外暴露和隐藏的端点
      exposure:
        include: "*"
      #允许跨域请求设置
      cors:
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    #健康信息
    health:
      show-details: always

# zipkin配置使用mq进行收集，使用es存储
zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      username: guest
      password: guest
      queue: zipkin
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://localhost:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/

