package com.blade.system.entity;

import com.blade.system.common.utils.GenIdUtil;
import tk.mybatis.mapper.annotation.KeySql;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Table(name = "base_menu")
public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.id
     *
     * @mbg.generated
     */
    @Id
    @KeySql(genId = GenIdUtil.class)
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.menu_path
     *
     * @mbg.generated
     */
    private String menuPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.menu_description
     *
     * @mbg.generated
     */
    private String menuDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * 菜单图标
     */
    private String menuIcon;

    /**
     * 权限编码
     */
    private String permissionCode;

    /**
     * 前端组件
     */
    private String menuComponent;

    /**
     * 状态
     */
    private String state;

    /**
     * 是否隐藏：1(是)、0(否)
     */
    private boolean hidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.id
     *
     * @return the value of base_menu.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.id
     *
     * @param id the value for base_menu.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.menu_name
     *
     * @return the value of base_menu.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.menu_name
     *
     * @param menuName the value for base_menu.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.menu_path
     *
     * @return the value of base_menu.menu_path
     *
     * @mbg.generated
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.menu_path
     *
     * @param menuPath the value for base_menu.menu_path
     *
     * @mbg.generated
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath == null ? null : menuPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.menu_description
     *
     * @return the value of base_menu.menu_description
     *
     * @mbg.generated
     */
    public String getMenuDescription() {
        return menuDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.menu_description
     *
     * @param menuDescription the value for base_menu.menu_description
     *
     * @mbg.generated
     */
    public void setMenuDescription(String menuDescription) {
        this.menuDescription = menuDescription == null ? null : menuDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.parent_id
     *
     * @return the value of base_menu.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.parent_id
     *
     * @param parentId the value for base_menu.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    public String getMenuIcon() {
        return menuIcon;
    }

    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public String getMenuComponent() {
        return menuComponent;
    }

    public void setMenuComponent(String menuComponent) {
        this.menuComponent = menuComponent;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public boolean isHidden() {
        return hidden;
    }

    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }

    @Override
    public String toString() {
        return "Menu{" +
                "id='" + id + '\'' +
                ", menuName='" + menuName + '\'' +
                ", menuPath='" + menuPath + '\'' +
                ", menuDescription='" + menuDescription + '\'' +
                ", parentId='" + parentId + '\'' +
                ", menuIcon='" + menuIcon + '\'' +
                ", permissionCode='" + permissionCode + '\'' +
                ", menuComponent='" + menuComponent + '\'' +
                ", state='" + state + '\'' +
                ", hidden=" + hidden +
                '}';
    }
}