package com.blade.system.entity;

import java.io.Serializable;

public class Operation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_operation.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_operation.operation_name
     *
     * @mbg.generated
     */
    private String operationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_operation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_operation.id
     *
     * @return the value of base_operation.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_operation.id
     *
     * @param id the value for base_operation.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_operation.operation_name
     *
     * @return the value of base_operation.operation_name
     *
     * @mbg.generated
     */
    public String getOperationName() {
        return operationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_operation.operation_name
     *
     * @param operationName the value for base_operation.operation_name
     *
     * @mbg.generated
     */
    public void setOperationName(String operationName) {
        this.operationName = operationName == null ? null : operationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_operation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", operationName=").append(operationName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}