package com.blade.system.entity;

import java.io.Serializable;

public class Permission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_permission.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_permission.permission_name
     *
     * @mbg.generated
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_permission.permission_code
     *
     * @mbg.generated
     */
    private String permissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_permission.permission_description
     *
     * @mbg.generated
     */
    private String permissionDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_permission.permission_type
     *
     * @mbg.generated
     */
    private String permissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_permission.id
     *
     * @return the value of base_permission.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_permission.id
     *
     * @param id the value for base_permission.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_permission.permission_name
     *
     * @return the value of base_permission.permission_name
     *
     * @mbg.generated
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_permission.permission_name
     *
     * @param permissionName the value for base_permission.permission_name
     *
     * @mbg.generated
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_permission.permission_code
     *
     * @return the value of base_permission.permission_code
     *
     * @mbg.generated
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_permission.permission_code
     *
     * @param permissionCode the value for base_permission.permission_code
     *
     * @mbg.generated
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_permission.permission_description
     *
     * @return the value of base_permission.permission_description
     *
     * @mbg.generated
     */
    public String getPermissionDescription() {
        return permissionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_permission.permission_description
     *
     * @param permissionDescription the value for base_permission.permission_description
     *
     * @mbg.generated
     */
    public void setPermissionDescription(String permissionDescription) {
        this.permissionDescription = permissionDescription == null ? null : permissionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_permission.permission_type
     *
     * @return the value of base_permission.permission_type
     *
     * @mbg.generated
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_permission.permission_type
     *
     * @param permissionType the value for base_permission.permission_type
     *
     * @mbg.generated
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType == null ? null : permissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_permission
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", permissionName=").append(permissionName);
        sb.append(", permissionCode=").append(permissionCode);
        sb.append(", permissionDescription=").append(permissionDescription);
        sb.append(", permissionType=").append(permissionType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}